image: oven/bun:alpine

stages:
    - build-production
    - build-test
    - build-main-test
    - build-media-test

build-production:
    stage: build-production
    environment:
        name: $CI_COMMIT_BRANCH
    only:
        - release
    variables:
    script:
        - bun install
        - bun run build


build-main-test:
    stage: build-main-test
    environment:
        name: $CI_COMMIT_BRANCH
    only:
        - test
    cache:
        paths:
            - node_modules/
    variables:
    script:
        - pwd
        - echo $CI_COMMIT_BRANCH $CI_COMMIT_REF_SLUG
        - env
        - bun install
        - bun run build:main
        - mc alias set minio $S3_HOST $S3_ACCESS_KEY $S3_SECRET_KEY
        - mc mirror --overwrite packages/main/out/ minio/$S3_PATH


build-media-test:
    stage: build-media-test
    environment:
        name: $CI_COMMIT_BRANCH
    only:
        - test
    cache:
        paths:
            - node_modules/
    variables:
    script:
        - pwd
        - echo $CI_COMMIT_BRANCH $CI_COMMIT_REF_SLUG
        - env
        - bun install
        - bun run build:media
        - mc alias set minio $S3_HOST $S3_ACCESS_KEY $S3_SECRET_KEY
        - mc mirror --overwrite packages/media/out/ minio/$S3_PATH
